### ISSUE TITLE
bad marshal data (unknown type code)

### ISSUE THREAD

**Issue by arunsehgals** [prabhat-123/Smart-AI-Attendance-System-With-AntiSpoofing#1]
getting this error in attendance with antispoof.. after uploading facenet_keras.h5 file from net

**Comment by prabhat-123** [comment]
have you installed all those dependencies?

**Comment by arunsehgals** [comment]
yes i have installed all dependencies as you mentioned in requirements.txt
can you provide facenet_keras.h5 file
facenet_keras.h5 file im using is of 88mb

**Comment by prabhat-123** [comment]
yes... you can download the model from this link and store it in models directory....  
facenet pretrained model file facenet_keras.h5 :-  https://drive.google.com/drive/folders/12aMYASGCKvDdkygSv1yQq8ns03AStDO_


Right now, requirements.txt is lacking some requirements... You can install it manually if some dependency error exists..... 

For requriements.txt make a new file named requirements.txt and copy all the requirements as stated below....
requirements.txt

absl-py==0.11.0
appdirs==1.4.3    
APScheduler==3.7.0
asgiref==3.2.7
astor==0.8.1
astroid==2.2.0
astunparse==1.6.3
beautifulsoup4==4.9.0
bs4==0.0.1
cachetools==4.0.0
certifi==2019.11.28
cffi==1.14.0
chardet==3.0.4
click==7.1.2
cmake==3.13.2
cx-Freeze==6.1
cycler==0.10.0
Cython==0.29.21
decorator==4.4.2
distlib==0.3.0
Django==3.0.5
filelock==3.0.12
Flask==1.1.2
flatbuffers==1.12
gast==0.3.3
gensim==4.0.1
gevent==20.6.1
google-auth==1.11.2
google-auth-oauthlib==0.4.1
google-pasta==0.2.0
greenlet==0.4.16
grpcio==1.32.0
gTTS==2.2.1
h5py==2.10.0
idna==2.9
imagecodecs==2020.2.18
imageio==2.8.0
importlib-metadata==1.5.0
imutils==0.5.3
isort==4.3.9
itsdangerous==1.1.0
Jinja2==2.11.2
joblib==0.14.1
Keras==2.3.1
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.2
kiwisolver==1.1.0
labelImg==1.8.3
lazy-object-proxy==1.3.1
lxml==4.5.0
Markdown==3.2.1
MarkupSafe==1.1.1
matplotlib==3.1.3
mccabe==0.6.1
mlxtend==0.17.2
mtcnn==0.1.0
networkx==2.4
nltk==3.5
numpy==1.19.5
oauthlib==3.1.0
onnx==1.8.0
opencv-contrib-python==4.2.0.34
opencv-python==4.4.0.46
opt-einsum==3.3.0
pandas==1.0.5
patsy==0.5.1
pdf2image==1.14.0
pickle-mixin==1.0.2
Pillow==8.1.0
protobuf==3.11.3
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.20
pylint==2.3.0
PyMySQL==1.0.2
pyparsing==2.4.6
pyPdf==1.13
PyQt5==5.14.2
PyQt5-sip==12.7.2
pytesseract==0.3.7
python-dateutil==2.8.1
pytz==2019.3
PyWavelets==1.1.1
PyYAML==5.3
regex==2021.3.17
requests==2.23.0
requests-oauthlib==1.3.0
rsa==4.0
schedule==1.0.0
scikit-image==0.17.2
scikit-learn==0.21.0
scipy==1.4.1
selenium==3.141.0
Shapely==1.7.0
six==1.15.0
sklearn==0.0
smart-open==5.0.0
soupsieve==2.0
sqlparse==0.3.1
statsmodels==0.12.2
tb-nightly==1.14.0a20190603
tensorboard==2.4.1
tensorboard-plugin-wit==1.6.0.post3
tensorflow==2.4.0
tensorflow-estimator==2.4.0
tensorflow-gpu==2.0.0
tensorflow-gpu-estimator==2.2.0
termcolor==1.1.0
tf-estimator-nightly==1.14.0.dev2019060501
threadpoolctl==2.1.0
tifffile==2020.5.11
tqdm==4.36.1
typing-extensions==3.7.4.3
tzlocal==2.1
urllib3==1.25.8
virtualenv==20.0.7
virtualenvwrapper-win==1.2.6
Werkzeug==1.0.0
wrapt==1.12.1
zipp==3.1.0
zope.event==4.4
zope.interface==5.1.0
